config/routes.rb
Kontax::Application.routes.draw do
  resources :contacts do 
    get   'scope/:scope',   to: 'contacts#index',  as: :scope,   on: :collection
    match 'case/:case',     to: 'contacts#update', as: :case,   on: :member, via: [:put, :patch]
    get   'notify/:notify', to: 'contacts#show',   as: :notify, on: :member
  end 
  resource  :dashboard, only: [:show]

  root to: 'dashboards#show'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  include PgSearch
  validates :name,  length: { minimum: 3 }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }

  validates :name,  uniqueness: true

  scope :trashed, -> { where(trash: true) }
  scope :not_trashed, -> { where(trash: false) }

  pg_search_scope :search_by_name_or_email,  against: [:name, :email], using: { tsearch: {prefix: true}}

  def self.search(query)
    query.present? ? search_by_name_or_email(query) : all 
  end

  def status
    self.trash ? 'trashed' : 'alive'
  end

  def move_to_trash
    self.trash = true
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Transponder::Transmission

  before_filter :set_gon_pusher

  before_action :set_fake_session

  def set_gon_pusher
    gon.pusher  = { key: ENV['PUSHER_KEY'] }
  end

  # in a real app you can use current_user.id or session or something
  def set_fake_session
    session[:who] ||= SecureRandom.hex(6)
    gon.who = session[:who]
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  respond_to :json, :html, :js

  def index
    @contacts = scoped_contacts
    respond_with @contacts
  end

  def new
    @contact = Contact.new
    respond_with @contact
  end

  def show
    @contact = Contact.where(id: params[:id]).first
    notification_response
  end

  def create 
    @contact = Contact.new(contact_params)
    if @contact.save
      respond_with @contact
      push_notify
    else
      xms_error @contact
    end
  end

  def edit
    @contact = Contact.where(id: params[:id]).first
    respond_with @contact
  end

  def update
    @contact = Contact.where(id: params[:id]).first
    if @contact.update_attributes(contact_params)
      respond_with @contact
      push_notify
    else
      xms_error @contact
    end
  end

  def destroy
    @contact = Contact.where(id: params[:id]).first
    if @contact.move_to_trash
      respond_with @contact
      push_notify
    else
      xms_error @contact
    end
  end

private

  def notification_response
    if params[:notify].present? 
      render params[:notify]
    else
      respond_with @contact
    end
  end

  def notify_data
    { resource: 'contacts', id: @contact.id, action: action_name, who: session[:who] }
  end

  def push_notify
    Pusher.trigger_async("contacts", "index", notify_data)
  end

  def scoped_contacts
    if params[:scope].present? and params[:scope] == 'trashed'
      Contact.trashed.search(params[:query])
    else
      Contact.not_trashed.search(params[:query])
    end
  end

  def contact_params
    params.require(:contact).permit(:name, :email, :trash)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def activeable_nav(text, path)
    active = request.path == path ? 'active' : 'inactive'
    content_tag :li, class: active do 
      link_to text, path
    end
  end

  def render_collection_with type, collection
    if collection.present?
      render partial: type, collection: collection
    else
      render "#{type.pluralize}/none"
    end
  end

  def render_sub_nav
    request.path.match(/(contacts)/) { |m| render "application/sub_nav/" + m.to_s }
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def contacts_heading
    if params[:case].present?
      params[:case].titleize
    else
      'All Contacts'
    end
  end

  def contacts_event
    params[:scope].present? ? params[:scope] : "index"
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/application/_footer.html.erb
<footer class='container'>
  <span>This app was created to demonstrate the capabilities of <a href='http://github.com/xpdr/transponder' target='_blank'>Transponder Gem</a>. You can get the source here:</span>  
  <span><a href='http://github.com/xpdr/kontax' target='_blank'>Kontax Source Code</a></span>
</footer>

app/views/application/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-6">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Kontax</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-6">
      <ul class="nav navbar-nav">
        <%= activeable_nav('Contacts', contacts_path) %>
      </ul>
      <%= render_sub_nav %>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/application/sub_nav/_contacts.html.erb
<%= form_tag request.path, class: 'navbar-form navbar-left contacts_search hide', remote: true do %>
  <div class='form-group'>
    <%= text_field_tag :query, nil,class: 'form-control', placeholder: "Search for someone", id: 'search-field' %>
  </div>
<% end %>
<ul class='nav navbar-nav navbar-right'>
  <li>
    <%= link_to new_contact_path, remote: true do %>
      <span class='glyphicon glyphicon-plus'></span> Add Contact
    <% end %>
  </li>
  <li>
    <%= link_to scope_contacts_path('trashed') do %>
      <span class='glyphicon glyphicon-trash'></span>
    <% end %>
  </li>
</ul>

app/views/contacts/_contact.html.erb
<%= div_for contact, class: 'col-md-3' do %>
  <div>
    <div class='name-tag'>
      <%= contact.name %>
    </div>
    <div class='detail'>
      <%= contact.email %>
    </div>
    <div class='actions'>
      <%= render "contacts/actions/#{contact.status}", contact: contact %>
    </div>
  </div>
<% end %>

app/views/contacts/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title">Edit <%= @contact.name %></h4>
    </div>
    <%= form_for @contact, remote: true do |f| %>
    <div class="modal-body">
        <div class='form-group'>
          <div class='input-group'>
            <span class='input-group-addon'><span class="glyphicon glyphicon-user"></span></span>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class='form-group'>
          <div class='input-group'>
            <span class='input-group-addon'><span class="glyphicon glyphicon-envelope"></span></span>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
        </div>
    </div>
    <div class='modal-footer'>
      <%= f.submit 'Save', class: 'btn btn-success' %>
    </div>
    <% end %>
  </div>
</div>

app/views/contacts/_none.html.erb
<div class='placeholder'>
  <span class='glyphicon glyphicon-user'></span> 
  <p class='lead'>No contacts were found.</p>
</div>

app/views/contacts/_notification.html.erb
Contact <strong><%= @contact.name %></strong> has been <%= params[:notify] || params[:case] || action_name %>

app/views/contacts/actions/_alive.html.erb
<%= link_to "Edit", edit_contact_path(contact), remote: true, class: 'btn btn-xs btn-default' %>
<%= link_to "Delete", contact_path(contact), method: :delete, remote: true, class: 'btn btn-xs btn-default' %> 

app/views/contacts/actions/_trashed.html.erb
<%= form_for contact, url: case_contact_path(contact, 'untrash'), remote: true do |f| %>
  <%= f.hidden_field :trash, value: false %>
  <%= f.submit "Put Back", class: 'btn btn-xs btn-default' %>
<% end %> 

app/views/contacts/create.js.erb
["#contacts", "<%= xms_event(action: params[:notify]) %>", 
  { "content" : "<%= j render @contact %>", 
    "notification" : "<%= j render 'notification' %>"
    }]

app/views/contacts/destroy.js.erb
["#contact_<%= @contact.id %>", "<%= xms_event(action: params[:notify]) %>", 
  { "notification": "<%= j render 'notification' %>"
    }]

app/views/contacts/edit.js.erb
["#modal-box", "<%= xms_event %>", "<%= j render 'form' %>"]

app/views/contacts/index.html.erb
<h1><%= contacts_heading %></h1>
<%= content_tag :div, id: 'contacts', class: 'row notification', data: { channel: "contacts", event: contacts_event} do %>
  <%= render_collection_with "contact", @contacts %>
<% end %>

app/views/contacts/index.js.erb
["div#contacts", "<%= xms_event %>", "<%= j render_collection_with 'contact', @contacts %>"]

app/views/contacts/new.js.erb
["#modal-box", "<%= xms_event %>", "<%= j render 'form' %>"]

app/views/contacts/show.js.erb
["#contact_<%= @contact.id %>", "<%= xms_event %>", "<%= j render @contact %>"]

app/views/contacts/update.js.erb
["#contact_<%= @contact.id %>", "<%= xms_event(action: params[:case] || params[:notify]) %>", 
  { "content": "<%= j render @contact %>", 
    "notification" : "<%= j render 'notification' %>" 
    }]

app/views/dashboards/show.html.erb
<div class="jumbotron">
  <h1>Kontax Demo App</h1>
  <p>
    This app was created to demo the <a href='http://xpdr.github.io/transponder' target='_blank'>Transponder</a> gem for rails.
  </p>
  <p>The source code for this app is here <a href='http://github.com/xpdr/kontax' targe='_blank'>Kontax on Github</a></p>
  <p>
    <%= link_to "View Contacts »", contacts_path, class: 'btn btn-lg btn-success' %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kontax</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller_name %> <%= action_name %>'>
  <%= render 'navigation' %>
  <div class='container'>
    <%= yield %>
  </div>
  <%= render 'footer' %>
  <div id='modal-box' class='modal fade'></div>
</body>
</html>